In [1]:
# En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. 
# Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones 
# y recordar como podemos iterar por un array.

In [2]:
import numpy as np
import random

In [3]:
# Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 
np.set_printoptions(precision=1, suppress=True)

array=np.random.rand(2,3,5)
array

array([[[0.9, 0.3, 0.6, 0.5, 0.1],
        [0.4, 0.7, 0.3, 0.6, 0.5],
        [0.8, 0. , 0.2, 0.4, 0.3]],

       [[0.3, 0.8, 0.3, 0.9, 0.6],
        [0. , 0.3, 0.2, 1. , 0.8],
        [0.7, 0.9, 0.2, 0.4, 0.4]]])

In [4]:
# Sobre el array creado anteriormente, extraed:
# Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

media= round((np.mean(array)),1)
media

0.5

In [5]:
np.where(array == 0.5)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [6]:
# Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

maximo=round((np.max(array)),1)
maximo

1.0

In [7]:
# Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

minimo=round((np.min(array)),1)
minimo

0.0

In [8]:
# Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

array_vacio= np.empty((array.shape), str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [24]:
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores 
# del primer array bajo las siguientes condiciones:
# Si el valor del array es igual que la media, se reemplaza por "A".
# Si el valor del array es mayor que la media, se reemplaza por "B".
# Si el valor del array es menor que la media, se reemplaza por "C".
# Si el valor es igual que el máximo, se reemplaza por "D".
# Si el valor es igual que el mínimo, se reemplaza por "E".



for x in range(0,2):
    for y in range(0,3):
        for z in range(0,5):
            if array[x][y][z]== media:
                array_vacio[x][y][z]= "A"
            elif array[x][y][z] > media:
                array_vacio[x][y][z]= "B"
            elif array[x][y][z] < media:
                array_vacio[x][y][z] = "C"
            elif array[x][y][z]== maximo:
                array_vacio[x][y][z] = "D"
            elif array[x][y][z]== minimo:
                array_vacio[x][y][z] = "E"
print(array_vacio)
        

[[['B' 'C' 'B' 'B' 'C']
  ['C' 'B' 'C' 'B' 'B']
  ['B' 'C' 'C' 'C' 'C']]

 [['C' 'B' 'C' 'B' 'B']
  ['C' 'C' 'C' 'B' 'B']
  ['B' 'B' 'C' 'C' 'C']]]


In [10]:
# Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. 
# Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
# En este caso:
# Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
# Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
# Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.


In [25]:
array_vacio_1 = array_vacio.reshape(30,)
array_vacio_1

array(['B', 'C', 'B', 'B', 'C', 'C', 'B', 'C', 'B', 'B', 'B', 'C', 'C',
       'C', 'C', 'C', 'B', 'C', 'B', 'B', 'C', 'C', 'C', 'B', 'B', 'B',
       'B', 'C', 'C', 'C'], dtype='<U1')

In [23]:
array_vacio_2=  np.empty(30)
array_vacio_2

array([0.9, 2. , 0.6, 0.5, 0.1, 0.4, 0.7, 0.3, 0.6, 0.5, 0.8, 0. , 0.2,
       0.4, 0.3, 0.3, 0.8, 0.3, 0.9, 0.6, 0. , 0.3, 0.2, 1. , 0.8, 0.7,
       0.9, 0.2, 0.4, 0.4])

In [31]:
for x in range(30):
    if (array_vacio_1[x] == "A") or (array_vacio_1[x] == "B"):
        array_vacio_2[x] = 1
    elif (array_vacio_1[x] == "C") or (array_vacio_1[x] == "D"):
        array_vacio_2[x] = 2
    elif array_vacio_1[x] == "E":
        array_vacio_2[x] = 3
print(array_vacio_2)

[1. 2. 1. 1. 2. 2. 1. 2. 1. 1. 1. 2. 2. 2. 2. 2. 1. 2. 1. 1. 2. 2. 2. 1.
 1. 1. 1. 2. 2. 2.]


In [34]:
# Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [33]:
array_numero = array_vacio_2.reshape(2,3,5)
array_numero

array([[[1., 2., 1., 1., 2.],
        [2., 1., 2., 1., 1.],
        [1., 2., 2., 2., 2.]],

       [[2., 1., 2., 1., 1.],
        [2., 2., 2., 1., 1.],
        [1., 1., 2., 2., 2.]]])