In [1]:
# Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.



In [2]:
# Cread un array de dos dimensiones de 5 filas y 3 columnas.
import random
import numpy as np 

array1=np.random.randint(0,100,(5,3))
array1 



array([[69, 90, 30],
       [15,  1, 57],
       [12, 73,  5],
       [16, 42, 15],
       [23, 46, 41]])

In [3]:
# Sobre el array creado anteriormente, extraed:
# El valor de la primera fila y la segunda columna.

array1[0,1]


90

In [4]:
# Los valores de la segunda fila y las dos primeras columnas.
array1[1,:2]

array([15,  1])

In [5]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.
array1[::2][:]

array([[69, 90, 30],
       [12, 73,  5],
       [23, 46, 41]])

In [6]:
# Extraed los valores que sean mayores que 0.5.
array1[array1>0.5]

array([69, 90, 30, 15,  1, 57, 12, 73,  5, 16, 42, 15, 23, 46, 41])

In [7]:
# Extraed los valores menores que 0.2 o mayores que 0.5
array1[(array1<0.2)|(array1>0.5)]

array([69, 90, 30, 15,  1, 57, 12, 73,  5, 16, 42, 15, 23, 46, 41])

In [8]:
# Cread dos array de tres dimensiones:
# El primero de 2 matrices, 5 filas y 3 columnas.

array2= np.random.randint(0,100,(2,5,3))
array2


array([[[32, 36, 25],
        [89, 89, 74],
        [40, 95, 44],
        [86, 53, 82],
        [61,  8, 42]],

       [[82, 49,  7],
        [ 5, 23, 67],
        [50,  5, 18],
        [96, 93, 97],
        [18, 86, 40]]])

In [9]:
# El segundo de 3 matrices, 2 filas y 5 columnas

array3=np.random.randint(0,100,(3,2,5))
array3

array([[[59,  5, 96, 71,  7],
        [ 8,  9, 37, 74, 18]],

       [[41, 69, 83,  8, 47],
        [ 1, 71, 63, 68, 20]],

       [[57, 53, 46, 63, 25],
        [34, 90, 60, 87, 22]]])

In [10]:
# Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

def propiedades(array):
    forma= array.shape
    print(f"La forma de tu array es{forma}")
    tamano= array.size
    print(f"El tamaño de tu array es {tamano}")
    dimension= array.ndim
    print(f"Tu array tiene dimension {dimension}")
    tipo_dato= array.dtype
    print(f"El tipo de dato que contiene tu array es {tipo_dato}")

In [11]:
propiedades(array2)

La forma de tu array es(2, 5, 3)
El tamaño de tu array es 30
Tu array tiene dimension 3
El tipo de dato que contiene tu array es int64


In [12]:
propiedades(array3)

La forma de tu array es(3, 2, 5)
El tamaño de tu array es 30
Tu array tiene dimension 3
El tipo de dato que contiene tu array es int64


In [13]:
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

def sumar(array1, array2):
    tamano1= array1.shape
    tamano2= array2.shape
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen la misma forma")

In [14]:
sumar(array2,array3)

Tus arrays no se pueden sumar dado que no tienen la misma forma


In [15]:
# Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
# .reshape()
# .transpose()
# Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

array_reshape=np.reshape(array3,(array2.shape))
array_reshape

array([[[59,  5, 96],
        [71,  7,  8],
        [ 9, 37, 74],
        [18, 41, 69],
        [83,  8, 47]],

       [[ 1, 71, 63],
        [68, 20, 57],
        [53, 46, 63],
        [25, 34, 90],
        [60, 87, 22]]])

In [22]:
sumar(array2,array_reshape) #ya se puede sumar

Se puede sumar
Tu resultado es [[[ 91  41 121]
  [160  96  82]
  [ 49 132 118]
  [104  94 151]
  [144  16  89]]

 [[ 83 120  70]
  [ 73  43 124]
  [103  51  81]
  [121 127 187]
  [ 78 173  62]]]


In [42]:
array_transpose = array3.transpose(1,2,0)
array_transpose

array([[[59, 41, 57],
        [ 5, 69, 53],
        [96, 83, 46],
        [71,  8, 63],
        [ 7, 47, 25]],

       [[ 8,  1, 34],
        [ 9, 71, 90],
        [37, 63, 60],
        [74, 68, 87],
        [18, 20, 22]]])

In [43]:
sumar(array2,array_transpose) #ya se puede sumar

Se puede sumar
Tu resultado es [[[ 91  77  82]
  [ 94 158 127]
  [136 178  90]
  [157  61 145]
  [ 68  55  67]]

 [[ 90  50  41]
  [ 14  94 157]
  [ 87  68  78]
  [170 161 184]
  [ 36 106  62]]]
