In [1]:
import numpy as np
import random


In [ ]:
# 1- ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?
np.random.random_sample()
0.47108547995356098 # random
type(np.random.random_sample())
<class 'float'>
np.random.random_sample((5,))
array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428]) # random

In [2]:
array1=np.random.randint(0,100,(2,2,2))
array1

array([[[23,  6],
        [ 6,  3]],

       [[39,  9],
        [50, 13]]])

In [4]:
# 2- Cread los siguientes arrays:
# Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

array_uniforme=np.round(np.random.uniform(low=0,high=10,size=(2,3,5)))
array_uniforme

array([[[ 1.,  9.,  3., 10.,  7.],
        [ 3.,  8.,  2.,  4., 10.],
        [ 3.,  7.,  6.,  2.,  1.]],

       [[ 9.,  3.,  1.,  8.,  1.],
        [ 5.,  5.,  9.,  5.,  8.],
        [ 2.,  7.,  3.,  8.,  4.]]])

In [5]:
valores_unicos_uniforme=np.unique(array_uniforme)
valores_unicos_uniforme

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
# Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, 
# con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.
array_binomial=np.round(np.random.binomial(10,0.3,size=(2,3,5)))
array_binomial

array([[[2, 2, 0, 5, 5],
        [1, 1, 0, 2, 2],
        [3, 4, 0, 2, 3]],

       [[4, 2, 4, 2, 4],
        [3, 2, 4, 4, 2],
        [3, 3, 2, 2, 1]]])

In [7]:
valores_unicos_binomial=np.unique(array_binomial)
valores_unicos_binomial

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 3- En esta lección hemos aprendido algunos métodos de teórias de conjuntos.
# Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

In [8]:
# Elementos comunes entre los dos arrays
interseccion=np.intersect1d(valores_unicos_uniforme,valores_unicos_binomial)
interseccion

array([1., 2., 3., 4., 5.])

In [9]:
# Unión de los dos arrays
union_arrays=np.union1d(valores_unicos_uniforme,valores_unicos_binomial)
union_arrays

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? 
# Extrae los valores númericos
elementos_unicos_uni=np.setdiff1d(valores_unicos_uniforme,valores_unicos_binomial)
elementos_unicos_uni

array([ 6.,  7.,  8.,  9., 10.])

In [ ]:
# Explicar cada uno de los outputs que os salgan. Que significa cada un
# a de estas operaciones que hemos ido extrayendo?


In [ ]:
# 4- Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [11]:
array1= np.random.randint(1,100, (80))
array1

array([30, 41, 50, 62, 10,  2, 26, 13, 64, 91, 46, 21, 96, 38, 32, 53, 76,
       38, 29, 98, 12, 26, 27, 35, 68, 49,  9, 93, 91, 38, 87, 17, 73, 85,
        2, 63, 49, 16, 11, 27, 93, 46, 13, 37, 77, 62, 52, 70, 74, 54, 20,
       47,  8, 23, 64, 68, 42, 54,  3, 64, 90, 15, 72, 54,  1, 97, 47, 10,
       31, 68, 83, 25, 64, 49, 18, 52, 97, 67, 66, 78])

In [12]:
array2= np.random.randint(1,100, (80))
array2

array([23, 58, 71, 24, 78, 87, 95, 24, 11,  5, 53, 67, 95, 42,  3,  1, 99,
       12, 30, 46, 95, 94, 71, 82, 31, 80, 86, 61, 20, 76, 40, 73, 93, 60,
       41, 75,  4, 16, 78, 43, 99, 42, 88,  1, 84, 56, 22, 28, 34, 13, 70,
       83, 64, 97, 12, 72,  9, 84, 63, 70, 35, 93, 28, 25, 11, 51, 98, 73,
       88, 66, 44, 59, 45, 46, 93, 95, 44, 97,  3, 95])

In [13]:
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

array3= np.setdiff1d(array1, array2)
array3

array([ 2,  8, 10, 15, 17, 18, 21, 26, 27, 29, 32, 37, 38, 47, 49, 50, 52,
       54, 62, 68, 74, 77, 85, 90, 91, 96])

In [14]:
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

array4= np.setdiff1d(array2,array1)
array4

array([ 4,  5, 22, 24, 28, 34, 40, 43, 44, 45, 51, 56, 58, 59, 60, 61, 71,
       75, 80, 82, 84, 86, 88, 94, 95, 99])

In [15]:
# Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

array5= np.intersect1d(array1, array2)
array5

array([ 1,  3,  9, 11, 12, 13, 16, 20, 23, 25, 30, 31, 35, 41, 42, 46, 53,
       63, 64, 66, 67, 70, 72, 73, 76, 78, 83, 87, 93, 97, 98])

In [ ]:
# ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

