In [ ]:


# 4- Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
# Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
# ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [ ]:
# 1- ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?
np.random.random_sample()
0.47108547995356098 # random
type(np.random.random_sample())
<class 'float'>
np.random.random_sample((5,))
array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428]) # random


In [1]:
import numpy as np
import random


AttributeError: module 'random' has no attribute 'random_sample'

In [7]:
array1=np.random.randint(0,100,(2,2,2))
array1

array([[[53, 10],
        [65, 36]],

       [[60, 14],
        [57, 23]]])

In [8]:
np.random.random_sample(array1)

TypeError: only integer scalar arrays can be converted to a scalar index

In [12]:
# 2- Cread los siguientes arrays:
# Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

array_uniforme=np.round(np.random.uniform(low=0,high=10,size=(2,3,5)))
array_uniforme

array([[[ 5.,  3.,  0.,  3.,  2.],
        [ 8.,  4.,  9.,  7.,  7.],
        [ 5.,  6.,  5.,  3.,  2.]],

       [[ 3.,  5.,  9.,  8.,  2.],
        [ 6.,  9.,  9.,  7.,  0.],
        [ 3., 10.,  2.,  8.,  3.]]])

In [17]:
valores_unicos_uniforme=np.unique(array_uniforme)
valores_unicos_uniforme

array([ 0.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
# Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, 
# con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.
array_binomial=np.round(np.random.binomial(10,0.3,size=(2,3,5)))
array_binomial

array([[[4, 4, 3, 3, 3],
        [2, 4, 2, 2, 4],
        [2, 1, 2, 2, 1]],

       [[4, 4, 6, 3, 2],
        [5, 5, 2, 1, 3],
        [1, 2, 0, 0, 5]]])

In [18]:
valores_unicos_binomial=np.unique(array_binomial)
valores_unicos_binomial

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# 3- En esta lección hemos aprendido algunos métodos de teórias de conjuntos.
# Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

In [19]:
# Elementos comunes entre los dos arrays
interseccion=np.intersect1d(valores_unicos_uniforme,valores_unicos_binomial)
interseccion

array([0., 2., 3., 4., 5., 6.])

In [20]:
# Unión de los dos arrays
union_arrays=np.union1d(valores_unicos_uniforme,valores_unicos_binomial)
union_arrays

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? 
# Extrae los valores númericos
elementos_unicos_uni=np.setdiff1d(valores_unicos_uniforme,valores_unicos_binomial)
elementos_unicos_uni

array([ 7.,  8.,  9., 10.])

In [ ]:
# Explicar cada uno de los outputs que os salgan. Que significa cada un
# a de estas operaciones que hemos ido extrayendo?
