In [ ]:
# Empezamos nuevo bloque de ejercicios de pair programming de NumPy.
# En el ejercicio de hoy vamos a empezar a trabajar con NumPy. 
# El objetivo de estos ejericicios es que creeis una serie de arrays, 
# y hagáis una serie de operaciones matemáticas con ellos.

In [1]:
import numpy as np
import random

In [ ]:
# Cread tres arrays: de una, dos y tres dimensiones.

In [3]:
#array 1 dimension
lista1= [8,19,3,7,22]
array1 = np.array(lista1)
array1


array([ 8, 19,  3,  7, 22])

In [13]:
# El array de 2 dimensiones debe ser de 2 filas y 3 columnas

array2=np.random.randint(0,10, (2,3))
array2




array([[8, 8, 5],
       [5, 3, 3]])

In [16]:
# El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

array3=np.random.randint(0,10, (2,3,5))
array3

array([[[7, 3, 5, 8, 6],
        [7, 0, 0, 2, 2],
        [9, 7, 3, 9, 4]],

       [[8, 3, 8, 5, 4],
        [8, 2, 4, 9, 7],
        [9, 3, 1, 9, 4]]])

In [18]:
# Chequed las las propiedades básicas de cada array que os hayáis creado. 
# Usad en una función que nos devuelva las propiedades de una array que le pasemos.

def propiedades(array):
    forma= array.shape
    print(f"La forma de tu array es{forma}")
    tamano= array.size
    print(f"El tamaño de tu array es {tamano}")
    dimension= array.ndim
    print(f"Tu array tiene dimension {dimension}")
    tipo_dato= array.dtype
    print(f"El tipo de dato que contiene tu array es {tipo_dato}")
    



In [21]:
propiedades(array3)

La forma de tu array es(2, 3, 5)
El tamaño de tu array es (2, 3, 5)
Tu array tiene dimension 3
El tipo de dato que contiene tu array es int64


In [23]:
# Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

array3_like = np.ones_like(array3)
array3_like

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [2]:
# Es el momento de hacer algunas operaciones entre arrays
# ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

def sumar(array1, array2):
    tamano1= array1.shape
    tamano2= array2.shape
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen la misma forma")

In [3]:
sumar(array2,array_identidad)

NameError: name 'array2' is not defined

In [38]:
# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra.
# La solución puede ser crear un array nuevo

#Para esto ampliaremos la funcion anterior

def sumar(array1, array2):
    tamano1= array1.size
    tamano2= array2.size
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen el mismo tamaño")
        array_nuevo= np.ones_like(array1)
        resultado2= array1+array_nuevo
        print (f"Hemos creado una matriz compatible con tu primer array y este es el resultado de su suma {resultado2}")
        

        

In [39]:
sumar(array2,array_identidad)

Tus arrays no se pueden sumar dado que no tienen el mismo tamaño
Hemos creado una matriz compatible con tu array y este es el resultado de su suma [[9 9 6]
 [6 4 4]]


In [ ]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
# Dividid las dos matricess