In [ ]:
# En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. 
# Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones 
# y recordar como podemos iterar por un array.







In [ ]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

   [[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

   [["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

In [ ]:
# 💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.
# Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
# En este caso:
# Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
# Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
# Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
# Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [1]:
import numpy as np
import random

In [8]:
# Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 
np.set_printoptions(precision=1, suppress=True)

array=np.random.rand(2,3,5)
array

array([[[0.2, 0.3, 0.4, 1. , 0.6],
        [0.6, 0.5, 0.9, 0.6, 1. ],
        [0.9, 0.9, 0.2, 0. , 0.1]],

       [[0.8, 0.4, 0.9, 0.4, 0.2],
        [0.4, 0.3, 0.5, 0.3, 0.4],
        [0.6, 0.4, 0.8, 0.8, 0.8]]])

In [15]:
# Sobre el array creado anteriormente, extraed:
# Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

media= round((np.mean(array)),1)
media

0.5

In [68]:
np.where(array == 0.5)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [16]:
# Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

maximo=round((np.max(array)),1)
maximo

1.0

In [17]:
# Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

minimo=round((np.min(array)),1)
minimo

0.0

In [70]:
# Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

array_vacio= np.empty((array.shape))
array_vacio

array([[[0.2, 0.3, 0.4, 1. , 0.6],
        [0.6, 0.5, 0.9, 0.6, 1. ],
        [0.9, 0.9, 0.2, 0. , 0.1]],

       [[0.8, 0.4, 0.9, 0.4, 0.2],
        [0.4, 0.3, 0.5, 0.3, 0.4],
        [0.6, 0.4, 0.8, 0.8, 0.8]]])

In [71]:
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores 
# del primer array bajo las siguientes condiciones:
# Si el valor del array es igual que la media, se reemplaza por "A".
# Si el valor del array es mayor que la media, se reemplaza por "B".
# Si el valor del array es menor que la media, se reemplaza por "C".
# Si el valor es igual que el máximo, se reemplaza por "D".
# Si el valor es igual que el mínimo, se reemplaza por "E".



for i in array_vacio:
    for e in i:
        for o in e:
            o= round(o, 1)
            if o == media:
                print()
                
                
            
       

        

0.5
0.5


In [ ]:
a[x][y][z]= "A", "B", "C"

In [76]:
for x in range(0,2):
    print(x)
    for y in range(0,3):
        print(y)
        for z in range(0,5):
            print(z)
            if a[x][y][z]== media:
                a[x][y][z]= "A"
            elif a[x][y][z] > media:
                a[x][y][z]= "B"
        

0
0
1
2
1
0
1
2


In [ ]:
if a[x][y][z]== media:
    a[x][y][z]= "A"
elif a[x][y][z] > media:
    a[x][y][z]= "B"

In [ ]:
a[x,y,z]= elemento a sustituir   #para sustituir 

In [73]:
for i in array_vacio:
    print(i)

[[0.2 0.3 0.4 1.  0.6]
 [0.6 0.5 0.9 0.6 1. ]
 [0.9 0.9 0.2 0.  0.1]]
[[0.8 0.4 0.9 0.4 0.2]
 [0.4 0.3 0.5 0.3 0.4]
 [0.6 0.4 0.8 0.8 0.8]]


In [74]:
for i in array_vacio:
    for e in i:
        print(e)

[0.2 0.3 0.4 1.  0.6]
[0.6 0.5 0.9 0.6 1. ]
[0.9 0.9 0.2 0.  0.1]
[0.8 0.4 0.9 0.4 0.2]
[0.4 0.3 0.5 0.3 0.4]
[0.6 0.4 0.8 0.8 0.8]


In [ ]:
for i in array_vacio:
    for e in i:
        for o in e:

In [ ]:
array [0][0][1]

In [64]:
if media in array:
    print('yes')
    