In [35]:
import numpy as np
import random


In [36]:
# 1- ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?
np.random.seed(42)
array_sample=np.random.sample((2,4))
array_sample

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [37]:
np.random.seed(42)
array_sample_2=np.random.sample((2,4))
array_sample_2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [38]:
# 2- Cread los siguientes arrays:
# Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

array_uniforme=np.round(np.random.uniform(low=0,high=10,size=(2,3,5)))
array_uniforme

array([[[ 6.,  7.,  0., 10.,  8.],
        [ 2.,  2.,  2.,  3.,  5.],
        [ 4.,  3.,  6.,  1.,  3.]],

       [[ 4.,  5.,  8.,  2.,  5.],
        [ 6.,  0.,  6.,  2.,  1.],
        [ 9., 10.,  8.,  3.,  1.]]])

In [39]:
valores_unicos_uniforme=np.unique(array_uniforme)
valores_unicos_uniforme

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
# Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, 
# con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.
array_binomial=np.round(np.random.binomial(10,0.3,size=(2,3,5)))
array_binomial

array([[[4, 3, 1, 3, 1],
        [5, 2, 4, 2, 3],
        [3, 2, 6, 4, 5]],

       [[5, 3, 5, 1, 2],
        [1, 2, 3, 2, 4],
        [2, 2, 3, 1, 4]]])

In [41]:
valores_unicos_binomial=np.unique(array_binomial)
valores_unicos_binomial

array([1, 2, 3, 4, 5, 6])

In [42]:
# 3- En esta lección hemos aprendido algunos métodos de teórias de conjuntos.
# Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

In [43]:
# Elementos comunes entre los dos arrays
interseccion=np.intersect1d(valores_unicos_uniforme,valores_unicos_binomial)
interseccion

#interseccion nos devuelve un array con todos los elementos comunes entre los dos array

array([1., 2., 3., 4., 5., 6.])

In [44]:
# Unión de los dos arrays
union_arrays=np.union1d(valores_unicos_uniforme,valores_unicos_binomial)
union_arrays

#union1d devuelve un array ordenado con los elementos resultantes de unir dos array.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? 
# Extrae los valores númericos
elementos_unicos_uni=np.setdiff1d(valores_unicos_uniforme,valores_unicos_binomial)
elementos_unicos_uni

#setdiff1d devuelve un array ordenado con los valores únicos que están en el primer array pero no en el segundo array.

array([ 0.,  7.,  8.,  9., 10.])

In [46]:
# 4- Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [47]:
array1= np.random.randint(1,100, (80))
array1

array([65, 89, 71,  9, 88,  1,  8, 88, 63, 11, 81,  8, 35, 35, 33,  5, 41,
       28,  7, 73, 72, 12, 34, 33, 48, 23, 62, 88, 37, 99, 44, 86, 91, 35,
       65, 99, 47, 78,  3,  1,  5, 90, 14, 27,  9, 79, 15, 90, 42, 77, 51,
       63, 96, 52, 96,  4, 94, 23, 15, 43, 29, 36, 13, 32, 71, 59, 86, 28,
       66, 42, 45, 62, 57,  6, 28, 28, 44, 84, 30, 62])

In [48]:
array2= np.random.randint(1,100, (80))
array2

array([75, 92, 89, 62, 97,  1, 27, 62, 77,  3, 70, 72, 27,  9, 62, 37, 97,
       51, 44, 24, 79, 59, 32, 96, 88, 52, 62, 58, 52, 12, 39,  2,  3, 56,
       81, 59,  2,  2, 92, 54, 87, 96, 97,  1, 19,  2, 53, 44, 90, 32, 70,
       32, 68, 55, 75, 56, 17, 38, 24, 69, 98, 70, 86, 11, 16, 97, 73, 59,
       70, 80, 93,  3, 20, 59, 36, 19, 90, 67, 19, 20])

In [49]:
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

array3= np.setdiff1d(array1, array2)
array3

array([ 4,  5,  6,  7,  8, 13, 14, 15, 23, 28, 29, 30, 33, 34, 35, 41, 42,
       43, 45, 47, 48, 57, 63, 65, 66, 71, 78, 84, 91, 94, 99])

In [50]:
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

array4= np.setdiff1d(array2,array1)
array4

array([ 2, 16, 17, 19, 20, 24, 38, 39, 53, 54, 55, 56, 58, 67, 68, 69, 70,
       75, 80, 87, 92, 93, 97, 98])

In [51]:
# Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

array5= np.intersect1d(array1, array2)
array5

array([ 1,  3,  9, 11, 12, 27, 32, 36, 37, 44, 51, 52, 59, 62, 72, 73, 77,
       79, 81, 86, 88, 89, 90, 96])

In [52]:
# ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

print(f"La cantidad de números contenidos en el array 1 y dos es la misma: {array1.size} y {array2.size} ya que son nuestros arrays 'originales', el array3 al solo representar de forma ordenada los valores presentes en array1 pero no en array2 cuenta con solo {array3.size} valores. Mientras que el array4 cuenta con los valores que hay en array2 pero no en array5, por lo que solo cuenta con {array4.size} valores. Para finalizar, array5 cuenta con {array5.size} valores ya que representa solo los valores que están presentes en ambos arrays, es decir los valores en común. ")

La cantidad de números contenidos en el array 1 y dos es la misma: 80 y 80 ya que son nuestros arrays 'originales', el array3 al solo representar de forma ordenada los valores presentes en array1 pero no en array2 cuenta con solo 31 valores. Mientras que el array4 cuenta con los valores que hay en array2 pero no en array5, por lo que solo cuenta con 24 valores. Para finalizar, array5 cuenta con 24 valores ya que representa solo los valores que están presentes en ambos arrays, es decir los valores en común. 
