In [ ]:
# Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.



In [6]:
# Cread un array de dos dimensiones de 5 filas y 3 columnas.
import random
import numpy as np 

array1=np.random.randint(0,100,(5,3))
array1 



array([[32, 32, 85],
       [85, 74, 14],
       [51, 42, 45],
       [27, 62,  1],
       [75, 18, 11]])

In [7]:
# Sobre el array creado anteriormente, extraed:
# El valor de la primera fila y la segunda columna.

array1[0,1]


32

In [11]:
# Los valores de la segunda fila y las dos primeras columnas.
array1[1,:2]

array([85, 74])

In [14]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.
array1[::2][:]

array([[32, 32, 85],
       [51, 42, 45],
       [75, 18, 11]])

In [16]:
# Extraed los valores que sean mayores que 0.5.
array1[array1>0.5]

array([32, 32, 85, 85, 74, 14, 51, 42, 45, 27, 62,  1, 75, 18, 11])

In [17]:
# Extraed los valores menores que 0.2 o mayores que 0.5
array1[(array1<0.2)|(array1>0.5)]

array([32, 32, 85, 85, 74, 14, 51, 42, 45, 27, 62,  1, 75, 18, 11])

In [20]:
# Cread dos array de tres dimensiones:
# El primero de 2 matrices, 5 filas y 3 columnas.

array2= np.random.randint(0,100,(2,5,3))
array2


array([[[89, 42, 81],
        [16, 58, 96],
        [83, 95, 93],
        [ 6, 62, 23],
        [86, 85,  0]],

       [[81, 76, 59],
        [24, 31, 48],
        [27, 20, 34],
        [20, 38, 48],
        [97, 22, 12]]])

In [22]:
# El segundo de 3 matrices, 2 filas y 5 columnas

array3=np.random.randint(0,100,(3,2,5))
array3

array([[[63, 22, 61, 61, 25],
        [50,  3, 40, 26, 39]],

       [[61, 82, 81, 37, 22],
        [17, 97, 37, 64, 23]],

       [[10, 62, 17,  6, 82],
        [10, 45, 47, 77, 99]]])

In [42]:
# Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

def propiedades(array):
    forma= array.shape
    print(f"La forma de tu array es{forma}")
    tamano= array.size
    print(f"El tamaño de tu array es {tamano}")
    dimension= array.ndim
    print(f"Tu array tiene dimension {dimension}")
    tipo_dato= array.dtype
    print(f"El tipo de dato que contiene tu array es {tipo_dato}")

In [43]:
propiedades(array2)

La forma de tu array es(2, 5, 3)
El tamaño de tu array es 30
Tu array tiene dimension 3
El tipo de dato que contiene tu array es int64


In [25]:
propiedades(array3)

La forma de tu array es(3, 2, 5)
El tamaño de tu array es (3, 2, 5)
Tu array tiene dimension 3
El tipo de dato que contiene tu array es int64


In [40]:
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

def sumar(array1, array2):
    tamano1= array1.shape
    tamano2= array2.shape
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen la misma forma")

In [41]:
sumar(array2,array3)

Tus arrays no se pueden sumar dado que no tienen la misma forma


In [45]:
# Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
# .reshape()
# .transpose()
# Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

array_reshape=np.reshape(array3,(array2.shape))
array_reshape

array([[[63, 22, 61],
        [61, 25, 50],
        [ 3, 40, 26],
        [39, 61, 82],
        [81, 37, 22]],

       [[17, 97, 37],
        [64, 23, 10],
        [62, 17,  6],
        [82, 10, 45],
        [47, 77, 99]]])

In [48]:
sumar(array2,array_reshape)

Se puede sumar
Tu resultado es [[[152  64 142]
  [ 77  83 146]
  [ 86 135 119]
  [ 45 123 105]
  [167 122  22]]

 [[ 98 173  96]
  [ 88  54  58]
  [ 89  37  40]
  [102  48  93]
  [144  99 111]]]
