In [1]:
# Empezamos nuevo bloque de ejercicios de pair programming de NumPy.
# En el ejercicio de hoy vamos a empezar a trabajar con NumPy. 
# El objetivo de estos ejericicios es que creeis una serie de arrays, 
# y hagáis una serie de operaciones matemáticas con ellos.

In [2]:
import numpy as np
import random

In [3]:
# Cread tres arrays: de una, dos y tres dimensiones.

In [4]:
#array 1 dimension
lista1= [8,19,3,7,22]
array1 = np.array(lista1)
array1


array([ 8, 19,  3,  7, 22])

In [5]:
# El array de 2 dimensiones debe ser de 2 filas y 3 columnas

array2=np.random.randint(0,10, (2,3))
array2




array([[8, 5, 6],
       [9, 4, 6]])

In [6]:
# El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

array3=np.random.randint(0,10, (2,3,5))
array3

array([[[0, 5, 2, 5, 3],
        [9, 6, 0, 6, 6],
        [3, 4, 9, 8, 4]],

       [[6, 8, 9, 1, 7],
        [5, 1, 3, 6, 6],
        [0, 9, 3, 8, 7]]])

In [28]:
# Chequed las las propiedades básicas de cada array que os hayáis creado. 
# Usad en una función que nos devuelva las propiedades de una array que le pasemos.

def propiedades(array):
    forma= array.shape
    print(f"La forma de tu array es{forma}")
    tamano= array.size
    print(f"El tamaño de tu array es {tamano}")
    dimension= array.ndim
    print(f"La dimension de tu array es {dimension}")
    tipo_dato= array.dtype
    print(f"El tipo de dato que contiene tu array es {tipo_dato}")
    



In [29]:
propiedades(array3)

La forma de tu array es(2, 3, 5)
El tamaño de tu array es 30
La dimension de tu array es 3
El tipo de dato que contiene tu array es int64


In [9]:
# Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

array3_like = np.ones_like(array3)
array3_like

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [40]:
# Es el momento de hacer algunas operaciones entre arrays
# ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

def sumar(array1, array2):
    tamano1= array1.shape
    tamano2= array2.shape
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen la misma forma")

In [41]:
sumar(array_identidad, array2)

Tus arrays no se pueden sumar dado que no tienen la misma forma


In [42]:
# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra.
# La solución puede ser crear un array nuevo

#Para esto ampliaremos la funcion anterior

def sumar2(array1, array2):
    tamano1= array1.shape
    tamano2= array2.shape
    if tamano1==tamano2:
        print ("Se puede sumar")
        resultado= array1+array2
        print (f"Tu resultado es {resultado}")
    else:
        print("Tus arrays no se pueden sumar dado que no tienen el mismo tamaño")
        array_nuevo= np.ones_like(array1)
        resultado2= array1+array_nuevo
        print (f"Hemos creado una matriz de solo unos compatible con tu primer array y este es el resultado de su suma {resultado2}")
        

        

In [43]:
sumar2(array_identidad, array2)

Tus arrays no se pueden sumar dado que no tienen el mismo tamaño
Hemos creado una matriz de solo unos compatible con tu primer array y este es el resultado de su suma [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [33]:
#debido a que el nuevo array creado está dentro de la función, lo sacamos como variable para los siguientes ejercicios
array_nuevo= np.ones_like(array_identidad)
array_nuevo

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
print (array_identidad*array_nuevo)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# Dividid las dos matricess
print( array_identidad/ array_nuevo)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
